version: '3.7'

networks:
  net-kafka:
    external: true

services:

  db:
    image: postgres
    container_name: db_auth
    ports:
      - "4545:5432"
    env_file:
      - .env-non-dev
    networks:
      - net-kafka
    volumes:
      - /etc/database/db-auth-mc:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis_auth
    ports:
      - "5454:6379"
    networks:
      - net-kafka
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: mc_auth
    ports:
      - "8001:8000"
    networks:
      - net-kafka
    restart: always
    depends_on:
      - redis
      - db


