version: '3.7'

networks:
  auth:
    driver: bridge 

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    env_file:
      - .env-non-dev
    ports:
      - "22181:2181"
    networks:
      - auth

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "19092:9092"
      - "9997:9997"
    networks:
      - auth
    depends_on:
      - zookeeper
    env_file:
      - .env-non-dev

  db:
    image: postgres
    container_name: db_auth
    ports:
      - "4545:5432"
    env_file:
      - .env-non-dev
    networks:
      - auth
    volumes:
      - /etc/database/db-auth-mc:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "5454:6379"
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: mc_auth
    ports:
      - "8001:8000"
    networks:
      - auth
    restart: always
    depends_on:
      - redis
      - db
      - kafka


