version: '3.7'

networks:
  auth:
    driver: bridge 

services:
  app:
    build: 
      context: .
    env_file:
      - .env
    container_name: mc_auth
    entrypoint: "/LKS-Auth-mc/docker/build.sh"
    ports:
      - 8000:8000
    networks:
      - auth
    depends_on:
      - db
    links:
      - db


  db:
    image: postgres
    container_name: db_auth
    ports:
      - 4545:5432
    env_file:
      - .env
    networks:
      - auth

  # redis:
  #   image: redis
  #   container_name: redis_cats
  #   ports:
  #     - 5454:6379
  #   networks:
  #     - auth
    
  