"""add name users

Revision ID: 10767298dcda
Revises: 189eddc25f1f
Create Date: 2024-12-08 01:02:24.174869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10767298dcda'
down_revision: Union[str, None] = '189eddc25f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('banned', sa.Boolean(), nullable=False))
    op.drop_column('users', 'baned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('baned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'banned')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
