"""empty message

Revision ID: f6678f8020a9
Revises: 5ce5183c1e84
Create Date: 2024-10-03 21:05:24.715961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6678f8020a9'
down_revision: Union[str, None] = '5ce5183c1e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cats', sa.Column('date_register', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('cats', sa.Column('data_update', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cats', 'data_update')
    op.drop_column('cats', 'date_register')
    # ### end Alembic commands ###
